### ISSUE TITLE
Sử dụng Electron để phát triển Apps

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#1]
1. Sử dụng cài  đặt Electron 
2. Tích hợp scripts download theme sử dụng wget vào, với các portable exe
   - Window riêng có bao gồm hướng dẫn sử dụng script, button để chạy
   -  wget.exe, node.exe và git.exe
3. Đăng ký app trên electron app list  (tìm hiểu cách đăng trước, tên để sau)
   - http://electron.atom.io/apps/
   - tên khả năng :   easyweb app  |   easyapp | ....

**Comment by baotnq** [comment]
@tungptvn  thêm tùng vào để cùng follow và phát triển

**Comment by baotnq** [comment]
@nemesisqp push lên git xong, em note ra 1 số tính năng cơ bản đã làm, để các anh em dễ dàng biết được nghe.

**Comment by nemesisqp** [comment]
- [x] landing page
- [x] browse page
- [x] call external git clone
- [x] skeleton for others page

**Comment by baotnq** [comment]
đã bổ sung đủ
