### ISSUE TITLE
Tính năng hiển thị Raw cho file Content

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#15]
- Có tab Raw hiển thị nội dung file Content
- Khi có lỗi không parse được file .md, thì hiện phần Raw này
- Cho phép lưu lại Raw sau khi điều chỉnh

**Comment by nemesisqp** [comment]
done 83e5180902be5bcb99b6758436970c5ce06102c2

![image](https://cloud.githubusercontent.com/assets/1621069/16327772/4fd3f004-39fd-11e6-8548-5c496715ccd2.png)

**Comment by baotnq** [comment]
Mới test lại, vẫn còn lỗi nghe ku, có show trong hình
![ewb-raw-content-error](https://cloud.githubusercontent.com/assets/15844016/16327846/0858e44a-39fe-11e6-94c1-f0b9c86ab20a.png)

**Comment by nemesisqp** [comment]
anh update lại đi, em né cái index.html nên commit thiếu cái load code-view.tag
