### ISSUE TITLE
Thêm mới file Content dựa vào file layout được chọn

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#16]
- Click vào "New -> Content" popup xuất hiện danh sách layout đang có
- Chọn 1 layout, sẽ tự động tạo ra 1 file .md có cấu trúc mặc định của config.html
- Khi bấm ưu hiển thị popup nhập tên file cần lưu, mặc định là tên không dấu của title, và lưu lại với tên này.

**Comment by nemesisqp** [comment]
done in 521a74185d98596cfebb202505657ced1739a8bd

**Comment by baotnq** [comment]
Một số lỗi sau:
- File mới tạo ra cần focus và hiển
- Khung cho sliders cần ngắn lại
- không lưu được trạng thái un-check box ( permalinks)
- giao diện bị chồng

![ewh-new_content](https://cloud.githubusercontent.com/assets/15844016/16374263/ed54ea3e-3c7f-11e6-9005-8e230debdbc2.png)

**Comment by baotnq** [comment]
Vì chúng ta sẽ sử dụng thuộc tính url để sinh ra link, nên khi tạo mới file Content.
Sau khi lưu, ngoài việc lưu "title" còn lưu luôn "url" chính là giá trị của file name nghe

**Comment by nemesisqp** [comment]
fixed in latest commit

**Comment by nemesisqp** [comment]
cái url thì hên xui vì anh còn chia trang nữa nên cái url chả có tác dụng gì cả

**Comment by baotnq** [comment]
em fix tính năng cho url nghe, cái này anh đã test và hoạt động ổn tại repo bên dưới rồi

[easyweb-metalsmith](https://github.com/easywebhub/easyweb-metalsmith)

**Comment by nemesisqp** [comment]
fixed in 35550172e7299bd1fccbf6878e0f92dfb63657c9

**Comment by baotnq** [comment]
test OK
