### ISSUE TITLE
Cho phép điều chỉnh nội dung Raw của file Content

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#17]
Raw Layout hiện tại không cho phép Edit và Save. Cần bổ sung tính năng Edit và Save lại.
Ngoài ra khi parse file content bị lỗi cấu trúc json, 
- thì hiển thị luôn Raw Layout,

**Comment by nemesisqp** [comment]
done in 1489ecb5bc13b62d6ee9d1c6261f5b3172da9aee

**Comment by baotnq** [comment]
test lại thấy không edit file Raw được, em fix xong nhớ note rõ cách em test nghe.

**Comment by nemesisqp** [comment]
file raw content hiện tại chỉ được edit khi json bị lỗi, anh muốn thì em để lúc nào cũng edit được

**Comment by baotnq** [comment]
Cho edit đi em, tuỳ lựa chọn của devs ah, nhưng nếu bị lỗi thì hightlight lên nghe.

**Comment by nemesisqp** [comment]
đã disable readOnly tren master
