### ISSUE TITLE
Bố trí lại button (Sign-in| Sync| Public)

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#21]
1. Xóa link bên trên để tiết kiệm không gian
   2 Thay bằng hàng button:
   - Sign-in: 
     - github account (nếu có tính năng tooltip khi hover thì càng tốt
     - Popup hiển thị giải thích rõ ràng hơn về github repository, ...
     - Xử lý hiển thị button sau khi signed-in
   - Sync: (tooltip: sync code to signed account) 
     - Hiển thị popup giải thích sơ lược và trạng thái hoàn thành
   - Public: (tooltip:  public to live )
     - hiển thị popup giải thích rõ ràng hơn
     - hiện ra live url để preview           http://user-nam.github.io/repo-name

![ewa-public-button](https://cloud.githubusercontent.com/assets/15844016/16515869/cbd5bb50-3f9e-11e6-81ff-dcc99363d01d.png)

**Comment by baotnq** [comment]
bố trí lại nút preview lên cùng hàng với nút (Sign-in | Sync | Public) luôn nghe

**Comment by nemesisqp** [comment]
done
![image](https://cloud.githubusercontent.com/assets/1621069/16550860/efdcd504-41da-11e6-8cd0-e0d045dd37d4.png)

**Comment by baotnq** [comment]
Chia thành 1 hàng như vậy rối lắm. 
Nên anh tạm thời bố trí lại cho tiện dụng hơn, có gì em test lại nghe.
![ewa-rearrange-button](https://cloud.githubusercontent.com/assets/15844016/16553058/1615a632-41f0-11e6-843b-cd991321f4c8.png)
