### ISSUE TITLE
Load vào website sau khi create new or clone

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#23]
Hiện tại sau khi tạo mới, vẫn ko load mở website này.
Cần load sau khi tạo mới hoặc clone

**Comment by nemesisqp** [comment]
new site xong có open site rồi mà anh

**Comment by baotnq** [comment]
Còn bị lỗi, open site nhưng phần cũ vẫn chưa ẩn đi
![ewa-load-after-create-error](https://cloud.githubusercontent.com/assets/15844016/16571090/d52cc9aa-427d-11e6-9335-36a71166eeca.png)

**Comment by baotnq** [comment]
test lại OK
