### ISSUE TITLE
Cho phép thêm hình ảnh local hoặc url vào website

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#25]
Cho phép users thêm hình ảnh vào website, hình ảnh local hoặc url

Các phần thực hiện:
- Bổ sung field Media vào Type
- lựa chọn local or url image
- Hình ảnh local sau khi users select sẽ được copy vào thư mục /content/images (hoặc thư mục phù hợp hơn do mình đặt)

**Comment by baotnq** [comment]
ưu tiên tính năng này nữa nghe @nemesisqp, vậy là đủ sử dụng để thay đổi nội dung website

**Comment by nemesisqp** [comment]
implemented in 96e7ab0aa398c66a6b33d9bfb4a77b257a14361e

**Comment by baotnq** [comment]
mới test thử bị lỗi, chọn file .md click Setting

**Comment by nemesisqp** [comment]
fixed, bug chạy trước khi init

**Comment by baotnq** [comment]
test sơ thấy OK với media rồi
