### ISSUE TITLE
Thuộc tính chỉ view cho field trong Config

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#29]
Một số field dữ liệu chỉ cho phép xem mà không thay đổi, ví dụ
- layout

Bổ sung thêm lựa chọn  **Only View** bên dưới **This field is required** trong Config

Trong phần Content, "Only View" field sẽ không cho phép edit, hiện tại "layout" phần cho phép edit

**Comment by nemesisqp** [comment]
implemented in e9a8a57cf342a5a1675cca10bb6cdf54c35beb3c

**Comment by baotnq** [comment]
test  OK
