### ISSUE TITLE
Bổ sung thêm type trong Config, tham khảo Contentful

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#30]
Bổ sung thêm 1 số type quan trọng
- Long Text
- Markdown Long Text

Hiển thị form tương ứng trong Content

**Comment by nemesisqp** [comment]
done in 909192866225a90251dc894fa74e06609cebcf23

**Comment by baotnq** [comment]
@easywebhub/vinaas-core-team  ghi nhớ các tính năng này nghe.
