### ISSUE TITLE
Tạo Standard và Advanced  EasyWebHub Template

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#32]
Chúng ta sẽ build easy website template tại repo bên dưới
https://github.com/easywebhub/easy-websites

Với
-  master:  cho Standard (không hỗ trợ precompiler như LESS, SASS)
- master-advanced: cho Advanced: hiện tại đã thực hiện  

Cập nhật lại EasyApp cho 2 template bên trên, default là Standard

**Comment by baotnq** [comment]
@nemesisqp  em ưu tiên cho Standard (master), và tiến hành thay thế source cũ, bảo đảm
- tạo website mới từ source này 
- website sau khi mới có thể watch với local node_modules của EasyApp

**Comment by nemesisqp** [comment]
implemented in 33c8ae490958601c0a8e6ebf2c8bddb2c89fc063

**Comment by baotnq** [comment]
- tạo website mới từ source này 
- website sau khi mới có thể watch với local node_modules của EasyApp

@nemesisqp , cái này đã test được chưa, ok thì chụp hình gửi anh biết nghe.

**Comment by nemesisqp** [comment]
em test thấy bt
![image](https://cloud.githubusercontent.com/assets/1621069/16795577/455fbfc6-4908-11e6-9c63-0a0c9503a304.png)

![image](https://cloud.githubusercontent.com/assets/1621069/16795551/1d43e03a-4908-11e6-85bc-e0ff1f99afc6.png)

**Comment by baotnq** [comment]
Standard test bị lỗi sau:
1. Create a new site với chọn Standard  (nên set Standard là default) đi
2. Sau khi tạo xong, chọn vào index.md mới bấm PreView được (ko chọn 1 file nào, ko bấm Preview)
3. Chạy Watch thì bị lỗi bên dưới (ko rõ có phải chạy install ko nữa)

![ewa-error](https://cloud.githubusercontent.com/assets/15844016/16799584/ceae1878-491b-11e6-8a57-660093682f20.png)

**Comment by baotnq** [comment]
Build và watch OK trên máy khác với Standard và Advanced website. Many thanks @nemesisqp .
@easywebhub/vinaas-core-team  các bạn cũng test thử xem
