### ISSUE TITLE
Thử gom thư viện trong node_modules

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#35]
Hiện tại có 2 thư mục node_modules trong EasyApp
- `/node_modules` : tạo ra sau khi Install easyapp
- `/tools/nodejs/node_modules` : dùng để chạy cho các sites tạo ra

Có cách nào gom chung vào 1 chỗ
- `/node_modules` để cùng cho chạy easyapp và chạy các sites bên trong

Tối ưu để build thành file exe cho gọn nhẹ

**Comment by nemesisqp** [comment]
làm chung với task #36
