### ISSUE TITLE
Build file cài đặt cho EasyApp

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#36]

**Comment by nemesisqp** [comment]
pc build app cần chạy command này 1 lần, console quyền admin

```
npm install -g electron-packager
```

để build file chạy script:

```
scripts/EWH-package.bat
```

build xong sẽ có file ewh.zip trong thư mục dist
- git 200 MB
- nodejs 95 MB
- electron ~80 MB

build xong ewh.zip ~160 MB vẫn khá nặng

**Comment by baotnq** [comment]
đã build và test ok
