### ISSUE TITLE
thêm config text với control textarea

### ISSUE THREAD

**Issue by tungptvn** [easywebhub/easyapp#40]
Dữ liệu kiểu text nhiều từ thì nên dùng control textarea

![image](https://cloud.githubusercontent.com/assets/11553588/16892736/cd360df6-4b47-11e6-9c7c-1c8063da446d.png)

**Comment by baotnq** [comment]
Cái này đã có trong issue khác rồi em, em cập nhật mới easyapp, phần text sẽ có Longtext tương ứng text area

**Comment by baotnq** [comment]
Cái này đã có trong issue khác rồi em, em cập nhật mới easyapp, phần text sẽ có Longtext tương ứng text area
