### ISSUE TITLE
Thay đổi trong VPS 15.38

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#41]
- Remove couchbase trong VPS 15.38 để giảm bộ nhớ sử dụng
- điều chỉnh api admin.lici.vn để trỏ tới couchbase mới : 
      http://104.168.94.152:8091/ui/index.html#/overview 
- bổ sung thêm email notification sử dụng domain easywebhub.com (hiện tại đã verify trên Sparkpot)
  - Hướng dẫn cách điều chỉnh
  - Thay đổi và cập nhật trên admin.lici.vn

@thinnv, @tungptvn  nắm thông tin sử dụng Sparkpot để send email miễn phí nghe.

**Comment by nemesisqp** [comment]
- [x] Remove couchbase trong VPS 15.38 để giảm bộ nhớ sử dụng
- [x] điều chỉnh api admin.lici.vn để trỏ tới couchbase mới : http://104.168.94.152:8091/ui/index.html#/overview

Sparkpost nó có cai SMTP relay, nó là 1 SMTP server bình thường, dotnet chỉ cần gửi mail như khi gửi bằng SMTP bình thường là xong
