### ISSUE TITLE
Import github account với EasyApp release bị lỗi

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#44]
- Sử dụng bản release [EasyApp](https://github.com/easywebhub/easyapp/releases/download/2.0/EasyApp_2.0.zip) cài đặt trên máy mới hoàn toàn, win server 2012
- Create website, Watch OK
- Import từ github thì bị lỗi, chỉ clone được thư mục build

Remote vào server  2012 để xem lỗi nghe
   nvthintt 
   n;-{weFRf_IXa(@
  host 104.196.17.235

**Comment by nemesisqp** [comment]
url project lỗi là gì vậy anh ? em lên đó test với project mới thì bt, test với https://github.com/easywebhub/medihub.git cũng ok 'test-mediahub'

**Comment by baotnq** [comment]
anh test với 1 account chưa đươc phân quyền write cho url này, nên nó bị
https://github.com/easywebhub/medihub.git

Hiện tại test với account của anh thì OK. Coi như lỗi này đã fix, chỉ cần lưu ý để thông báo người dùng sau này thôi.

@easywebhub/vinaas-core-team : EasyApp sẽ import github account bị lỗi, nếu account đăng nhập ko có quyền Write của repo import, các bạn lưu ý về bug này.

**Comment by nemesisqp** [comment]
thêm escape username password cho trường hợp username hoặc pass có @ và các ký tự đặc biệt khác trong commit b7db9a53d6fe7161fe8377c9c93b082543f220e7

**Comment by baotnq** [comment]
test ok
