### ISSUE TITLE
Ẩn nút Init

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#47]
Ẩn nút Init sau khi init hoặc với imported website. Có thể dùng thông tin git nằm trong website để ẩn nút Init này

**Comment by nemesisqp** [comment]
có trong e72c35705ee8f58d33237eaa069615358f510c75

**Comment by baotnq** [comment]
"create new site" with Standard selection, no "Init" button show, please check again and for another cases

**Comment by nemesisqp** [comment]
fixed in c3d9188f29ad62d9b907ce899c3f6756610931ca

**Comment by baotnq** [comment]
test OK
