### ISSUE TITLE
Vài góp ý về App sau khi thêm phòng khám và bác sỹ

### ISSUE THREAD

**Issue by thinnv** [easywebhub/easyapp#50]
- a Bảo: sau khi sử dụng app phiên bản mới nhất để nhập data cực kỳ bất tiện:
-  Các field vượt quá bị khuất:
  ![image](https://cloud.githubusercontent.com/assets/6780364/17075749/dd6b16d2-50c7-11e6-8118-cffd300ed159.png)

khi nhập không tự hiện lên trên mà hiện nữa vời dẫn đến tình trang phải copy ra notepadd để soạn thảo-->người dùng cực kỳ thao tác mất thời gian
1. Khi chỉnh sửa nội dung từng filed rất khó vì khi đánh 1 chữ thì con trỏ về cuối dòng.

**Comment by baotnq** [comment]
@nemesisqp  em xem các góp ý của Thìn và cải thiện nghe.

**Comment by nemesisqp** [comment]
fixed in f6826e6cc1bcdec711988b5ea046c5bc90dc4fb2

> Khi chỉnh sửa nội dung từng filed rất khó vì khi đánh 1 chữ thì con trỏ về cuối dòng.

cái này field type nào bị vậy ? tại bữa trước có fix rồi

**Comment by baotnq** [comment]
test OK
