### ISSUE TITLE
Vẫn show home tag trong landing tax sau khi click vào "home" button

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#53]
Sau khi click vào "home" button và trở về trang landing, như vẫn còn hiển thị trang chi tiết bên dưới như hình đính kèm

![ewa-not-hide-home-tag](https://cloud.githubusercontent.com/assets/15844016/17199145/e8f53cea-54a4-11e6-8c85-8be44fca6de9.png)

**Comment by nemesisqp** [comment]
fixed in d6a93f468a8d0b4683cf1f549ee7f95dfd186f17

**Comment by baotnq** [comment]
test OK
