### ISSUE TITLE
Vài điều chỉnh nhỏ

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#54]
Trang bắt đầu của EasyWeb Builder là "landing" thay thế cho trang "login

```
curPage = riot.mount('landing')[0];
```

Kích thước home editor cho side-bar ngắn lại, và phần editor dài hơn

`class="col-xs-4 col-sm-4 col-md-3 col-lg-3"`

`class="col-xs-8 col-sm-8 col-md-9 col-lg-9 tab-pane"`

**Comment by nemesisqp** [comment]
done
