### ISSUE TITLE
"Build" button not work

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#55]
- For import from github  `https://github.com/easywebhub/medihub`
- For create new site

**Comment by baotnq** [comment]
tuy nhiên nút "Refresh" thì lại hoạt động

**Comment by nemesisqp** [comment]
fixed in 95e55d86de6454950ade2516dbdece0d7f85695c

**Comment by baotnq** [comment]
tối ưu hơn:
- Build dev ẩn vào trong và nằm dưới Refresh
- Bổ sung nút Refresh Dev để refresh cho trường hợp Build Dev này.

**Comment by baotnq** [comment]
test OK
