### ISSUE TITLE
Deploy not work

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#56]
Test the Init, Sync and Deploy for repo, see for more details

https://github.com/easywebhub/deploy-gh-1/tree/master

After Init, Sync and Deploy, the master branch and gh-pages not work

**Comment by nemesisqp** [comment]
flow sao vậy anh nãy giờ em chưa ra giống vậy được

**Comment by baotnq** [comment]
Đã tìm ra nguyên nhân và hướng xử lý vấn đề này.
**Sau khi Init, cần phải Refresh (build again) rồi deploy thì mới có hiệu quả.**

Ngoài ra, github.io có thể ko hiển thị sau lần đầu deploy, hãy sửa lại trong  {{global.github-url}}, build và deploy lại.
@easywebhub/vinaas-core-team các bạn trong team lưu ý.
