### ISSUE TITLE
Thay đổi domain trong EasyWebBuilder

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#57]
- thêm button "Change Domain" dropdown ẩn bên trong button "Deploy"
- Click button, hiện textbox điền domain của website và ghi đè giá trị cũ và lưu thẳng vào /asset/CNAME.txt

**Comment by nemesisqp** [comment]
name của github là CNAME mà anh, nó đâu có .txt

**Comment by nemesisqp** [comment]
implemented in 1eafd8e3318ffbe13493cdb08e129e4d06516a7c

**Comment by baotnq** [comment]
khi không điền domain và bấm cancel hiển thị báo lỗi ko đúng.
Yêu cầu:  Bấm Cancel cần đóng lại popup mà ko warning gì cả

**Comment by nemesisqp** [comment]
fixed, em quên béng mất cái null check a62e7a7e0b990806ce82a861e39720eeb219e323

**Comment by baotnq** [comment]
test OK
