### ISSUE TITLE
Order các property trong config

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#60]
Cần hiển thị property trong Content Form theo thứ tự:
- thứ tự được định nghĩa trong config bởi order
- order càng lơn càng nằm trên cùng của content form
- order thấp nhất là 0
- order được sinh ra tự động lần đầu tiên dựa theo thứ tự trong Json.
- layout và slug có 2 thứ tự cố định rất lớn 100 và 99
- Dev có thể thay đổi giá trị order trong config

@nemesisqp  xem và xử lý nghe

**Comment by nemesisqp** [comment]
cho phép thay đổi order bằng drag drop config field trong config view, mặc định slug + layout lên top
9306a02a8d636c259fbc38cd6d564bb1668d1f33

**Comment by baotnq** [comment]
Test OK
