### ISSUE TITLE
sync lỗi

### ISSUE THREAD

**Issue by tungptvn** [easywebhub/easyapp#63]
@nemesisqp  a check chức năng sync giùm em nhé, lúc đầu em sync để lấy code mới nhất về thì ok, lần sau e thêm 1 bài viết (thêm 1 file .md), sync lại thì gặp lỗi này.
![image](https://cloud.githubusercontent.com/assets/11553588/17277956/d0b69d7c-5779-11e6-94c9-eebc3c49fd4b.png)

**Comment by nemesisqp** [comment]
trong thư mục của cái site nó có folder .git vô trong lấy file "config" gửi qua skype đi tại nó chứa login info không nên upload trên này

**Comment by baotnq** [comment]
test OK
