### ISSUE TITLE
No md field, bug with {{{markdown field-name}}}

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#78]
See screenshot

![ewh-no-md-field](https://cloud.githubusercontent.com/assets/15844016/18375937/c0bb799a-7684-11e6-8678-ee94ab4ca913.png)

**Comment by nemesisqp** [comment]
fixed in b9c4668f819e780b05e12278c9c2ebe53535bc8a

**Comment by baotnq** [comment]
TestOK
