### ISSUE TITLE
`Open` button to open the folder of a file

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyapp#83]
To edit source files easier using external editor (VsCode, Atom), 
- add a `Open` button, on right side of breadcrumb tag of EasyBuilder
- show `Open` for Layout files

**Comment by nemesisqp** [comment]
done in 9b4b957dacf8423f267008d7ada3a130878e4c94
click direct item in breadcrumb instead of right aligned button or right click context menu

**Comment by baotnq** [comment]
click enabled with `Layout` files only

**Comment by baotnq** [comment]
Test OK
